((lambda ()
   (interactive)
   (setq **STACK-ROOT** (rel-path "."))
   (add-hook 'before-save-hook
             '(lambda () (interactive)
                (whitespace-cleanup)
                (py/codestyle)))
   (require 'python)
   (require 'emacs_setup)
   ; (setq python-shell-interpreter (format "%s/emacs_ipython" **STACK-ROOT**))
   (defvar py-test-runner 'pytest)
   (venv-set-location **STACK-ROOT**)
   (venv-workon "venv")
   (setq jedi:complete-on-dot t)
   (setq jedi:use-shortcuts t)
   (add-hook 'python-mode-hook 'jedi:setup)
   (py-test-setup-default **STACK-ROOT** :chdir **STACK-ROOT**)))
